services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads  # persistir KYC
      - ./backend/instance:/app/instance
    environment:
      - FLASK_ENV=development
      - STREAM_API_KEY=3qbb5mez5zqm
      - STREAM_API_SECRET=yx2rc4rffddg786ppxg7zby4h8j8xwz9kxqvxneh622hyyteuj9xqkzqd847cfeq
      - APP_TIMEZONE=America/Panama
      - TZ=America/Panama
      - BREVO_API_KEY=${BREVO_API_KEY}
      - FRONTEND_URL=http://localhost:3000
      - SENDER_EMAIL=no-reply@myabogapp.com
      - APP_NAME=AbogApp
      - ADMIN_CREATE_SECRET=CristianoRonaldoBetterThanMessi
      - JWT_SECRET_KEY=superdevsecret
      - BREVO_TMPL_LAWYER_APPROVED=1  # cambia por tu ID real
      - BREVO_TMPL_LAWYER_REJECTED=2
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend